authors: []
blacklist:
- leg_detector
- people_tracking_filter
- imagesift
- face_detector
- jsk_interactive_marker
- jsk_interactive
- jsk_interactive_test
- jsk_pcl_ros
- jsk_perception
build_space: build_debug
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=~Debug
- -DCATKIN_ENABLE_TESTING=OFF
- -DOMPL_BUILD_DEMOS=OFF
- -DOMPL_BUILD_TESTS=OFF
- -DOMPL_BUILD_PYTESTS=OFF
- -DOMPL_BUILD_PYBINDINGS=ON
devel_layout: linked
devel_space: devel_debug
extend_path: null
extends: null
install: false
install_space: install_debug
isolate_install: false
jobs_args: []
licenses: TODO
log_space: logs_debug
maintainers: []
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
